name: getx_pattern
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  
  get: 4.6.5
  get_storage: ^2.0.3
  velocity_x: 3.4.0
  gredu_common: ^0.0.6
  google_fonts: ^2.1.0
  responsive_grid: ^2.0.0
  material_design_icons_flutter: ^5.0.6595
  flutter_desktop_folder_picker: ^0.0.1
  click_to_copy: ^0.0.1
  recase: ^4.0.0
  # --------------------------------------------------
  flutter: 
    sdk: flutter

  # desktop only
  process_run: ^0.12.3+2
  bitsdojo_window: 0.1.1 
  window_manager: ">=0.2.3"
  flutter_acrylic:
    git:
      url: https://github.com/alexmercerind/flutter_acrylic.git
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  very_good_analysis: ^2.4.0
  change_app_package_name: ^1.1.0
      
flutter: 
  uses-material-design: true

get_cli: 
  sub_folder: false

